spring.application.name=O-Registro-da-Guilda
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=audit
spring.datasource.username=appuser
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

